### ISSUE TITLE
Broken Translatable core & custom module dropdown menu

### ISSUE THREAD

**Issue by ArchBlood** [humhub/translation#31]
Would seem that now most translations are broken and only show `%` this also affects custom modules that have translatable files

![Screenshot_3](https://user-images.githubusercontent.com/35392110/90177936-36e54d80-dd79-11ea-9ea9-6503fec90678.png)

Throws this on trying, no error logs
```log
{
    "url": "/translation/translate/index?moduleId=directory&language=zh-CN",
    "status": 404,
    "response": {
        "error": true,
        "message": ""
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"\"}",
        "responseJSON": {
            "error": true,
            "message": ""
        },
        "status": 404,
        "statusText": "Not Found"
    },
    "dataType": "json",
    "error": true,
    "message": "",
    "errorThrown": "Not Found",
    "validationError": false
}
```

**Comment by luke-** [comment]
I can't replicate this on our translation server. 
Are there any specific steps to reproduce the problem?

**Comment by ArchBlood** [comment]
Not exactly sure, all I did was enable the module while having custom modules with custom namespaces, example being the scroll up module and a few others from @GreenMeteor 🤔

**Comment by luke-** [comment]
Strange, so this does not affect our translation community?

**Comment by ArchBlood** [comment]
Doesn't look like it affect the translation site unless the translation site also use custom modules with custom namespaces?

**Comment by luke-** [comment]
Hmm just tested it, and the scrollup modules works fine with a custom namespace.

**Comment by ArchBlood** [comment]
I've disabled and re-enabled the module some of the options have come back but not all are available still. :thinking:

**Comment by ArchBlood** [comment]
Although once I try updating the translation it throws the same error... :disappointed:

**Comment by luke-** [comment]
Hmm I cannot reproduce this with the "scrollup" module on my local environment

**Comment by buddh4** [comment]
I could not recreate the broken core modules as in your screenshot, but I probably found the problem with your custom modules. Currently the directory name of your module needs to match the module id. So it does not work if your module directory name is e.g. `humhub-modules-scrollup` in needs to be `scrollup`.

**Comment by buddh4** [comment]
I did also run `php yii message/extract-module scrollup`

**Comment by ArchBlood** [comment]
I only got the scrollup module translation working when changing the namespace but got most of core working again, as for error logs didn't show any @buddh4
