### ISSUE TITLE
Special characters like "&" are purified

### ISSUE THREAD

**Issue by ArchBlood** [humhub/translation#63]
See the following from the translation site;

https://translate.humhub.org/content/perma?id=94564

### Possible solution
```php
<?php

namespace humhub\modules\translation\models\parser;

use yii\helpers\HtmlPurifier;
use HTMLPurifier_ConfigSchema;

class TranslationPurifier extends HtmlPurifier
{
    /**
     * @inheritDoc
     */
    public static function configure($config)
    {
        // Set HTMLPurifier configuration
        $config->set('HTML.Doctype', 'HTML 4.01 Transitional');
        $config->set('Attr.EnableID', true);

        // Allow specific tags and attributes
        $config->set('HTML.Allowed', 'p,b,i,u,s,a[href|target],img[src|alt],ul,ol,li,blockquote,code,pre,span,hr,br,strong');

        // Allow non-ASCII characters and special symbols like '&'
        $config->set('Core.EscapeNonASCIICharacters', false);
        $config->set('Core.Encoding', 'UTF-8');
        $config->set('Cache.DefinitionImpl', null); // Disable caching to prevent issues with updated config

        // To avoid escaping inside the attributes
        $def = $config->getHTMLDefinition(true);
        $def->addAttribute('a', 'href', new HTMLPurifier_AttrDef_URI());
        $def->addAttribute('img', 'src', new HTMLPurifier_AttrDef_URI());
    }
}
```

**Comment by yurabakhtin** [comment]
@ArchBlood Thanks for the suggested solution but it didn't help and I could not find another config which solves the issue, so I have fixed it by another way. The char `&` is not converted to `&amp;` after saving now:

![amp](https://github.com/humhub/translation/assets/6995524/d0596e54-b2cf-455b-971f-605957f78bed)

@luke- PR https://github.com/humhub/translation/pull/64

**Comment by ArchBlood** [comment]
> @ArchBlood Thanks for the suggested solution but it didn't help and I could not find another config which solves the issue, so I have fixed it by another way. The char `&` is not converted to `&amp;` after saving now:
> 
> ![amp](https://private-user-images.githubusercontent.com/6995524/346523861-d0596e54-b2cf-455b-971f-605957f78bed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTc1NTksIm5iZiI6MTcyMDg1NzI1OSwicGF0aCI6Ii82OTk1NTI0LzM0NjUyMzg2MS1kMDU5NmU1NC1iMmNmLTQ1NWItOTcxZi02MDU5NTdmNzhiZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMDc1NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQxMDg2YzBkYWY4ODgxNGU5YzFiNTE5NGZiMTIzYmZmZjQ0NTM2NDljMGE2YjBkYjdkNjA0YjVjM2M4Njg1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A23N2bVLPqvWQNMIDONwq1Q-aPdZotjcKMrYL2cezzA)
> 
> @luke- PR #64

@yurabakhtin couldn't this be used in combination for possible future issues?

http://htmlpurifier.org/doxygen/html/classHTMLPurifier__Config.html

```php
if ($config === null) {
    $config = \HTMLPurifier_Config::createDefault();
    self::configure($config);
}
```

**Comment by yurabakhtin** [comment]
@ArchBlood I see you want to replace current code:

```php
    $result = parent::process($content, $config);
```

with:

```php
    // If no configuration is provided, create a default configuration
    if ($config === null) {
        $config = HTMLPurifier_Config::createDefault();
        self::configure($config);
    }

    // Create a new HTMLPurifier instance with the provided or created config
    $purifier = new HTMLPurifier($config);

    // Purify the content
    $result = $purifier->purify($content);
```

but why don't you want to use the specific config instead of the config that is inside the `parent::process()`? :

```php
    $configInstance = \HTMLPurifier_Config::create($config instanceof \Closure ? null : $config);
    $configInstance->autoFinalize = false;
    $purifier = \HTMLPurifier::instance($configInstance);
    $purifier->config->set('Cache.SerializerPath', \Yii::$app->getRuntimePath());
    $purifier->config->set('Cache.SerializerPermissions', 0775);

    static::configure($configInstance);
    if ($config instanceof \Closure) {
        call_user_func($config, $configInstance);
    }

    return $purifier->purify($content);
```

I didn't investigate the code deeply but probably the `HTMLPurifier_Config::createDefault()` does the same what the `parent::process()` does. Or please tell what issue you found so we need to use your code, for example, please provide samples with wrong results instead of expecting, otherwise we prefer to keep the current code as is.
Thanks.

**Comment by ArchBlood** [comment]
> @ArchBlood I see you want to replace current code:
> 
> ```
>     $result = parent::process($content, $config);
> ```
> 
> with:
> 
> ```
>     // If no configuration is provided, create a default configuration
>     if ($config === null) {
>         $config = HTMLPurifier_Config::createDefault();
>         self::configure($config);
>     }
> 
>     // Create a new HTMLPurifier instance with the provided or created config
>     $purifier = new HTMLPurifier($config);
> 
>     // Purify the content
>     $result = $purifier->purify($content);
> ```
> 
> but why don't you want to use the specific config instead of the config that is inside the `parent::process()`? :
> 
> ```
>     $configInstance = \HTMLPurifier_Config::create($config instanceof \Closure ? null : $config);
>     $configInstance->autoFinalize = false;
>     $purifier = \HTMLPurifier::instance($configInstance);
>     $purifier->config->set('Cache.SerializerPath', \Yii::$app->getRuntimePath());
>     $purifier->config->set('Cache.SerializerPermissions', 0775);
> 
>     static::configure($configInstance);
>     if ($config instanceof \Closure) {
>         call_user_func($config, $configInstance);
>     }
> 
>     return $purifier->purify($content);
> ```
> 
> I didn't investigate the code deeply but probably the `HTMLPurifier_Config::createDefault()` does the same what the `parent::process()` does. Or please tell what issue you found so we need to use your code, for example, please provide samples with wrong results instead of expecting, otherwise we prefer to keep the current code as is. Thanks.

@yurabakhtin after looking into it more, there are a few key differences that I have found which my modification doesn't support so after looking into it I'm fine with using the parent process method;

The key differences are additional handling for cache paths, permissions, and closure-based configurations are provided in Yii 2's `HTMLPurifier`  where as mine does not provide this, the key similarities are both provide methods to create an `HTMLPurifier` instance and purify the content, allowing for configuration customization, and that's all.
